# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml

# Python configuration
python:
  # equivalent to pip install .[docs]
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs