# mkdocs.yml

site_name: Phytospatial
site_description: The open-source standard for enhanced forest inventories
site_url: https://phytospatial.readthedocs.io/
repo_url: https://github.com/Louis-Gm/phytospatial
repo_name: Louis-Gm/phytospatial

theme:
  name: material
  logo: assets/images/logo/logo-transparent-small.png
  favicon: assets/images/logo/logo-black-small.png
  custom_dir: docs/overrides

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.copy
    - navigation.top

  font:
    text: Ovo
    code: Roboto Mono

  palette:
      scheme: slate

extra_css:
  - stylesheets/theme.css
  - stylesheets/home.css
  - stylesheets/global.css

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - search
  - mkdocs-jupyter
  - gen-files:
      scripts:
        - scripts/create_reference_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
  - include-markdown

nav:
  - Home: index.md
  - Getting Started:
      - "Installation": installation.md
      - "Basic Usage": usage.md
  - Tutorials:
      - "Pipeline Introduction": examples/extraction_pipeline.ipynb
  - API Reference: reference/
  - Articles:
      - "Phytospatial Blog": articles/blog.md
  - About:
      - "About Phytospatial": about.md
      - "Acknowledgements": acknowledgements.md
      - "License": license.md
  - Contributing:
      - "Contributing": contributing/contributing.md
      - "Code of Conduct": contributing/code_of_conduct.md

      - "Releasing": contributing/releasing.md
